### ISSUE TITLE
Unable to find some of the usages

### ISSUE THREAD

**Issue by ezisazis** [s4cha/Localize#14]
The script can't find those usages where (let's say, the line is too long) a key is broke into a new line

```
NSLocalizedString(
@"string_key", nil)]
```

Can be easily fixed by doing:

```
NSLocalizedString(@"string_key", nil)]
```

Although it would be nice if the script could find the first one too

**Comment by sionleroux** [comment]
If you just want to allow newline after ( you can do: ```NSLocalizedString(\n?otherstuff``` the `\n?` is the important part (optional newline).
