### ISSUE TITLE
[Feature] - Optional Alphabetic sort 

### ISSUE THREAD

**Issue by floriangbh** [s4cha/Localize#2]
Allowing to configure the alphabetic sort

**Comment by s4cha** [comment]
Thinking about it now I remember that sorting the files alphabetically allowed for easier (and faster) warning generation. What I mean is that if an issue is found in the `en` file line 3, we can raise the warnings on the same line in other files, say `es` or `fr`.

Not sorting them automatically means keys could be ordered differently so we will need extra processing to find the right corresponding line in every file.

This shouldn't be too complex but it's something we need to keep in mind :)

**Comment by s4cha** [comment]
My bad after checking in the code, it's already relying on dictionaries rather that line numbers so it shouldn't be that big of a deal :)

**Comment by s4cha** [comment]
```swift
/*
 Sanitizing files will remove comments, empy lines and order your keys alphabetically.
 */
let sanitizeFiles = true
```
Set to false, it will prevent the script form modifying your files :)

**Comment by floriangbh** [comment]
This seems to work fine, thank you ;-)
